CREATE DATABASE IF NOT EXISTS retro_press CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE retro_press;
CREATE TABLE users(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,display_name VARCHAR(120) NOT NULL,role ENUM('admin','editor') NOT NULL DEFAULT 'editor',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE categories(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,slug VARCHAR(140) NOT NULL UNIQUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE posts(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,slug VARCHAR(255) NOT NULL UNIQUE,excerpt TEXT NULL,content MEDIUMTEXT NOT NULL,image_url VARCHAR(1000) NULL,category_id INT UNSIGNED NULL,author_id INT UNSIGNED NOT NULL,status ENUM('draft','published') NOT NULL DEFAULT 'draft',is_featured TINYINT(1) NOT NULL DEFAULT 0,published_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_posts_public(status,published_at),INDEX idx_posts_category(category_id),CONSTRAINT fk_posts_category FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT fk_posts_author FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB;
INSERT INTO users(email,password_hash,display_name,role) VALUES('admin@example.com','$2y$12$ofHJI84/hukKnq0JYgrKpOPCKosvJjPg1TX00BimW/6V1T.c9Nkv2','Главный редактор','admin');
INSERT INTO categories(name,slug) VALUES('Главное','glavnoe'),('Город','gorod'),('Культура','kultura'),('Технологии','tehnologii'),('Мнения','mneniya');
INSERT INTO posts(title,slug,excerpt,content,category_id,author_id,status,is_featured,published_at) VALUES
('Новый выпуск: город просыпается','novyy-vypusk-gorod-prosypaetsya','Первый демонстрационный материал вашей цифровой газеты.','<p>Это демонстрационная статья. Замените её настоящей новостью через панель редакции.</p><h2>Газетный ритм</h2><p>Макет построен на крупных заголовках, колонках, контрастных линейках и бумажной фактуре.</p>',1,1,'published',1,NOW()),
('Редакция открывает рубрику о культуре','redakciya-otkryvaet-rubriku-o-kulture','Короткие заметки, интервью и рецензии появятся в новой рубрике.','<p>Используйте рубрики, чтобы разделять материалы по темам и собирать удобный архив.</p>',3,1,'published',0,NOW());
